### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by glebm** [colszowka/simplecov#404] opened 2015-08-08 01:53 UTC
SimpleCov had been very fast for my [i18n-tasks](https://github.com/glebm/i18n-tasks) gem until I added an AST parser to it using [whitequark/parser](https://github.com/whitequark/parser) that uses ragel.

Now running with SimpleCov is 14 times slower:

``` console
$ git clone https://github.com/glebm/i18n-tasks
$ cd i18n-tasks && git checkout 0.9-dev && bundle
$ bundle exec rspec spec/i18n_spec.rb  # without simplecov (~1s)
$ COVERAGE=1 bundle exec rspec spec/i18n_spec.rb  # with simplecov (~14s)
```

**Comment by bf4** [comment] 2015-08-20 02:19
HI @glebm which Ruby platform and version are you on? Which SimpleCov are you on? Please review the [CONTRIBUTING guidelines](https://github.com/colszowka/simplecov/blob/master/CONTRIBUTING.md).  

I wonder if the problem is not SimpleCov but is the Coverage module itself.  Instead of starting simplecov, try (typing this without verifying):

```ruby
if ENV["COVERAGE"].to_i == 2
end
```

**Comment by bf4** [comment] 2015-08-27 06:38
Hi @glebm Just checking in. Are you still interested in investigating this?

**Comment by glebm** [comment] 2017-01-22 22:12
Apologies for the late response. I could no longer reproduce the issue in October.
However, a user has just opened the same issue in the i18n-tasks repo, so I've directed them here.

**Comment by bf4** [comment] 2017-01-24 20:10
@buren @glebm re: https://github.com/colszowka/simplecov/issues/404#issuecomment-132854240 

Can you help me check if the issue with with SimpleCov or the Coverage module in the stdlib?


Set `gem 'simplecov', require: false` in your gemfile, and make sure you don't require it anywhere in your code.  

Where you would have required it or called SimpleCov.start, instead run:

```ruby
  require 'coverage'
  require 'pp'
  Coverage.start
  at_exit do
    pp Coverage.result
  end
```

And let me know if the speed issue persists.

**Comment by PragTob** [comment] 2017-01-24 21:08
Also, the _soon to be released(tm)_ version of simplecov (current master), comes with a couple of performance improvements :)

**Comment by PragTob** [comment] 2017-02-04 12:42
Seems to be the Coverage stdlib that is actually slow, e.g. I did what @bf4 asked and time results are basically the same as with running Simplecov for me. 


```
# just coverage library (printing removed)
tobi@speedy ~/github/i18n-tasks $ time COVERAGE=true bundle exec rspec spec/i18n_spec.rb 
/home/tobi/.asdf/installs/ruby/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/tobi/.asdf/installs/ruby/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
warning: parser/current is loading parser/ruby24, which recognizes
warning: HEAD-compliant syntax, but you are running 2.4.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
..

Finished in 19.21 seconds (files took 0.2799 seconds to load)
2 examples, 0 failures


real	0m19.814s
user	0m19.680s
sys	0m0.056s

# Simplecov timing
tobi@speedy ~/github/i18n-tasks $ time COVERAGE=true bundle exec rspec spec/i18n_spec.rb 
/home/tobi/.asdf/installs/ruby/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/tobi/.asdf/installs/ruby/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
warning: parser/current is loading parser/ruby24, which recognizes
warning: HEAD-compliant syntax, but you are running 2.4.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
..

Finished in 19.56 seconds (files took 0.28703 seconds to load)
2 examples, 0 failures

Coverage report generated for RSpec to /home/tobi/github/i18n-tasks/coverage. 1575 / 2487 LOC (63.33%) covered.

real	0m20.356s
user	0m20.204s
sys	0m0.068s

```

**Comment by PragTob** [comment] 2017-08-12 11:14
Closing as apparently sadly we can't really do anything

**Closed by PragTob** 2017-08-12 11:14 UTC
