### ISSUE TITLE
Missing model coverage with FactoryBot

### ISSUE THREAD

**Issue by lxbrito** [colszowka/simplecov#736] opened 2019-07-24 20:49 UTC
Defining the class of a factory not using quotation marks, although valid syntax, causes the model coverage to be ignored (0%).

FactoryBot.define do
  factory :my_class, class: MyClass do
instead of
  factory :my_class, class: 'MyClass' do

causes the glitch, even if the factory is not used in the model's spec. 

In my case it also affected the ApplicationRecord coverage, even with other AR models having 100% coverage.
 
-----------------------------------------------------------------------
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
Rails 6.0.0.rc2
rspec-core (3.8.2)
rspec-expectations (3.8.4)
factory_bot_rails (5.0.2)
factory_bot (5.0.2)
factory_bot_rails (5.0.2)

**Comment by PragTob** [comment] 2019-07-27 17:33
:wave: 

Hi there thanks for your report!

Would you be able to reproduce in a small repo? For me this smells a little bit like some sort of setup problem as the only difference that I can think of that this would make is that `MyClass` triggers rails' autoloading of that class and that might have to do with the missing results.

Are you sure that simplecov is required and started first thing? No spring funkyness?

**Comment by PragTob** [comment] 2019-12-03 09:55
@lxbrito hi there, any update on this? :)

**Comment by PragTob** [comment] 2020-01-16 14:06
Closing due to missing feedback

**Closed by PragTob** 2020-01-16 14:06 UTC
Labels: Awaiting Feedback
