### ISSUE TITLE
track_files doesn't seem to be working

### ISSUE THREAD

**Issue by katelovescode** [colszowka/simplecov#486] opened 2016-04-08 20:25 UTC
When I add a new model under my models folder, but don't add the spec, then run `bundle exec rspec`, SimpleCov still shows 100% coverage.

Here's the top of my spec_helper.rb:

```
require 'simplecov'
require 'simplecov-rcov'

SimpleCov.start do
  add_filter 'spec'
  add_filter 'config'
  add_group 'Controllers', '/app/controllers'
  add_group 'Models', '/app/models'
  add_group 'Helpers', '/app/helpers'
  add_group 'Views', '/app/views'
  add_group 'Mailers', '/app/mailers'
  track_files "/app/**/*.rb"
end

class SimpleCov::Formatter::MergedFormatter
  def format(result)
     SimpleCov::Formatter::HTMLFormatter.new.format(result)
     SimpleCov::Formatter::RcovFormatter.new.format(result)
  end
end

SimpleCov.formatter = SimpleCov::Formatter::MergedFormatter
```

Here's the relevant tree structure:

```
- root
- app
-- models
--- employee.rb
--- quickbase_entry.rb [NEW]
--- time_entry.rb
--- toggl_entry.rb
- spec
-- models
--- employee_spec.rb
--- time_entry_spec.rb
--- toggl_entry.rb
```

And when I run `bundle exec rspec`:

```
Finished in 0.75808 seconds (files took 2.65 seconds to load)
44 examples, 0 failures, 7 pending

Coverage report generated for RSpec to /Users/user/Projects/project/coverage. 65 / 65 LOC (100.0%) covered.
```

When I've run into this before, if I add a blank `quickbase_entry_spec.rb` into the models folder under spec, it will show coverage % drop.  But isn't that what `track_files` is supposed to do automatically?

**Comment by kateklemp** [comment] 2016-04-08 21:36
Just as a follow-up, I added a `quickbase_entry_spec.rb` file to the `/spec/models` folder and added these lines to it:

```
require 'rails_helper'

RSpec.describe QuickbaseEntry, type: :model do
end
```

And now it's being shown as uncovered:
```
Finished in 0.73727 seconds (files took 1.85 seconds to load)
44 examples, 0 failures, 7 pending

Coverage report generated for RSpec to /Users/user/Projects/project/coverage. 75 / 97 LOC (77.32%) covered.
```

So I can verify that it picks up when the file is manually created.

**Comment by patrick-gleeson** [comment] 2016-06-08 09:39
Hi @kateklemp,
I believe the issue is the leading slash you've put in the `track_files` argument. I've been playing with a legacy codebase, and found:
```ruby
SimpleCov.start do
  track_files "app/**/*.rb"
end
```
leads to:
```
7163 / 11744 LOC (60.99%) covered
```
Whereas:
```ruby
SimpleCov.start do
  track_files "/app/**/*.rb"
end
```
leads to:
```
7163 / 8645 LOC (82.86%) covered
```

**Comment by kateklemp** [comment] 2016-07-08 20:49
OK, I will give this a shot as soon as I can; that particular repo has been decommissioned, so I'll try on a new one when I get a chance.  Thanks for looking into this.

**Comment by PragTob** [comment] 2017-02-04 12:16
Hey, any update here how it went? @katelovescode :)

**Comment by emaiax** [comment] 2017-03-14 22:48
This is also happening to me with `app/helpers`, even though RSpec are really testing my helpers.

Thoughts?

**Comment by PragTob** [comment] 2017-03-15 07:59
Hi there @emaiax - I need more data for that. Like what simplecov version are you running, what are the filters and track_files you have configured and most ideally there'd be a small sample app reproducing the problem that makes our lives 100 times easier as the more concrete information we have, the better we can track down the problem - so an exact repro case is the best.

**Comment by emaiax** [comment] 2017-03-27 18:51
Hey @PragTob, I made my config from scratch all over again and things started to work as expected.
I don't know what was messing things up, but it's ok now.

Sorry about the false negative. 👍

**Comment by PragTob** [comment] 2017-03-27 19:30
Thanks for getting back!

I'll close this one out then :)

**Closed by PragTob** 2017-03-27 19:30 UTC
