### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by colszowka** [colszowka/simplecov#372] opened 2015-02-18 14:47 UTC
We are getting a bunch of seemingly random failures, on different ruby versions when building on travis. 

Locally everything works fine for me and the failing ruby versions vary across builds.

https://travis-ci.org/colszowka/simplecov/builds

**Comment by bf4** [comment] 2015-02-19 03:40
Duplicate of https://github.com/colszowka/simplecov/issues/362

**Comment by colszowka** [comment] 2015-02-19 08:04
Ah, thanks Ben :)

**Closed** 2015-02-19 10:56 UTC
Labels: Bug
