### ISSUE TITLE
while line has no coverage but while body does (when upgrading from 2.5.7 to 2.6.5)

### ISSUE THREAD

**Issue by JonJagger** [colszowka/simplecov#802] opened 2019-12-29 16:51 UTC
I'm running a simple rack-based http server inside a docker container as part of [cyber-dojo](https://cyber-dojo.org).

When my base image is Alpine:3.10
Then coverage is as expected:
<img width="1186" alt="simplecov-expected-coverage" src="https://user-images.githubusercontent.com/252118/71559861-d956f780-2a5a-11ea-9a5f-7e5ff78e198b.png">

$ ruby -e "puts RUBY_DESCRIPTION"
`ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-musl]`

The Base image's Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    docile (1.3.2)
    json (2.3.0)
    minitest (5.13.0)
    ruby-prof (1.1.0)
    simplecov (0.17.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)

PLATFORMS
  ruby

DEPENDENCIES
  json
  minitest
  ruby-prof
  simplecov

BUNDLED WITH
   2.0.2
```

The actual image's Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    bigdecimal (2.0.0)
    daemons (1.3.1)
    eventmachine (1.2.7)
    oj (3.10.0)
    prometheus-client (1.0.0)
    rack (2.0.8)
    thin (1.7.2)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (>= 1, < 3)

PLATFORMS
  ruby

DEPENDENCIES
  bigdecimal
  oj
  prometheus-client
  rack
  thin

BUNDLED WITH
   2.0.2
```

When my base image is Alpine:3.11
Then coverage is unexpected. Note that line 42 is a while and reports _no_ coverage, but it's body (line 43,44,45) _does_ have coverage (24 hits). The `same?` method reports all its lines are covered.
<img width="1159" alt="simplecov-unexpected-screenshot" src="https://user-images.githubusercontent.com/252118/71559862-e96ed700-2a5a-11ea-8bb4-a01013560dac.png">

$ ruby -e "puts RUBY_DESCRIPTION"
`ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]`

The Base image's Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    docile (1.3.2)
    json (2.3.0)
    minitest (5.13.0)
    ruby-prof (1.1.0)
    simplecov (0.17.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)

PLATFORMS
  ruby

DEPENDENCIES
  json
  minitest
  ruby-prof
  simplecov

BUNDLED WITH
   2.0.2
```

The actual image's Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    bigdecimal (2.0.0)
    daemons (1.3.1)
    eventmachine (1.2.7)
    oj (3.10.0)
    prometheus-client (1.0.0)
    rack (2.0.8)
    thin (1.7.2)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (>= 1, < 3)

PLATFORMS
  ruby

DEPENDENCIES
  bigdecimal
  oj
  prometheus-client
  rack
  thin

BUNDLED WITH
   2.0.2
```

Maybe this is similar to #764 ?

**Comment by PragTob** [comment] 2019-12-31 15:56
@JonJagger I'm 99% sure that's a coverage bug then as the ruby base version changed but the simplecov version didn't. You don't happen to have a base image with ruby 2.7 to try that out?

also thanks for the reporting! :green_heart:

**Comment by JonJagger** [comment] 2019-12-31 16:50
Alas I don't.

**Comment by PragTob** [comment] 2020-01-03 10:23
@JonJagger So, without a reproduction script so that I can check if the bug is fixed on ruby 2.7 I can't determine whether that's the problem or not (although I strongly believe it is as the only thing that changed was the ruby version and we have no conditional code that'd be different between those 2 versions). Input appreciated :

**Comment by JonJagger** [comment] 2020-01-03 16:26
The base OS is Alpine and there is no Alpine package for Ruby 2.7 yet.
When one becomes available I will build a new image with it and report back.

**Comment by JonJagger** [comment] 2020-01-05 11:35
I tried Alpine 3.11 with the 0.18.0beta1 gem.
It's still Ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
But the anomaly has now gone away...
<img width="1161" alt="Screen Shot 2020-01-05 at 11 33 46" src="https://user-images.githubusercontent.com/252118/71779627-5fb98f00-2faf-11ea-89ff-90299a312a58.png">

**Comment by PragTob** [comment] 2020-01-05 12:02
ehhhh - wat?

Ah yes, that's #764 then because that also mentions it magically goes away when turning on branch coverage (which it seems you did). Also thanks for trying out 0.18.0! :tada: 

Closing now as iirc it's fixed on main line ruby.

**Closed by PragTob** 2020-01-05 12:02 UTC
Labels: Awaiting Feedback, Possible Coverage Bug
