### ISSUE TITLE
Controllers non-deterministically not being covered

### ISSUE THREAD

**Issue by sriedel** [colszowka/simplecov#438] opened 2015-12-07 08:33 UTC
I'm running simplecov with rspec 3.4, padrino 0.13.0 under ruby 2.2.3 and fakefs (in case this could be relevant).

I've been observing for a while now (also under rspec 3.2 and 3.3, and padrino 0.12.5) that some controller specs won't cover the corresponding controllers. They specs themselves are being run, however it's up to chance if the corresponding code is considered covered or not.

What is odd is that the issue appears only in the controllers (31 specs out of over 1400 specs in the code base). How can I debug the issue to pin down the cause of the issue?

**Comment by RohanM** [comment] 2016-08-01 06:33
I'm seeing something similar after switching our app from `selenium` to `poltergeist` (with simplecov 0.12.0). Before the switch, we'd get consistent coverage results. After, the coverage would change run to run by ~5%. However, I see the issue appearing in controller, model and lib specs.

**Comment by PragTob** [comment] 2019-12-03 16:15
This um... is weird and sorry for the long silence :see_no_evil: 

Is this still something you're seeing right now or might you even have a sample repo to reproduce this?

**Comment by PragTob** [comment] 2020-01-16 14:10
Closing due to missing feedback

**Closed by PragTob** 2020-01-16 14:10 UTC
Labels: Awaiting Feedback
