### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by howdoicomputer** [colszowka/simplecov#370] opened 2015-02-07 01:04 UTC
Coverage is generated but I get this stack trace after every test run.

```
/Users/tyler.hampton/.rvm/gems/ruby-2.1.5/gems/multi_json-1.10.1/lib/multi_json/adapter.rb:19:in `load': JSON::ParserError (MultiJson::ParseError)
	from /Users/tyler.hampton/.rvm/gems/ruby-2.1.5/gems/multi_json-1.10.1/lib/multi_json.rb:119:in `load'
	from /Users/tyler.hampton/.rvm/gems/ruby-2.1.5/gems/simplecov-0.9.1/lib/simplecov/json.rb:10:in `parse'
	from /Users/tyler.hampton/.rvm/gems/ruby-2.1.5/gems/simplecov-0.9.1/lib/simplecov/last_run.rb:10:in `read'
	from /Users/tyler.hampton/.rvm/gems/ruby-2.1.5/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:66:in `block in <top (required)>'
```

**Comment by bf4** [comment] 2015-02-08 07:59
Thanks for the bug report.  Without more information, though, there's not much we can do.  From the stack trace, it looks like it's reading a file in from the file system.  Check what json files you have in your coverage dir.

**Comment by colszowka** [comment] 2015-03-12 09:43
@howdoicomputer Can you please try deleting the coverage dir and regenerating from scratch? It seems something hicked up and cleaning up probably will resolve it.

Closing, please feel free to reopen if you can reproduce this after cleaning up.

**Closed by colszowka** 2015-03-12 09:43 UTC
Labels: Bug
